-- ============================================================
-- PUVELA — GO-LIVE: migration + import 67 sản phẩm (chạy 1 lần)
-- Supabase → SQL Editor → dán CẢ FILE → Ctrl/Cmd+A → Run
-- ============================================================

-- 1) migration: thêm cột items cho orders (để checkout lưu đơn)
alter table orders add column if not exists items jsonb;

-- 2) import catalog (reset + 67 sản phẩm):
-- ============================================================
-- PUVELA — IMPORT CATALOG (67 sản phẩm) từ danh sách của bạn
-- Giá = ước lượng mặt bằng thị trường VN, chỉnh lại theo giá nhập thật.
-- Ảnh = placeholder, thay bằng ảnh thật (Supabase Storage) sau.
-- Chạy trong Supabase SQL Editor SAU khi đã chạy schema.sql.
-- ============================================================

-- RESET: xoá catalog cũ để thay bằng danh sách này (chạy CẢ FILE một lần). An toàn: orders lưu ở orders.items jsonb.
delete from order_items; delete from product_variants; delete from product_collections; delete from products; delete from brands;

-- BRANDS
insert into brands(slug,name) values
  ('afnan','Afnan'),
  ('armaf','Armaf'),
  ('burberry','Burberry'),
  ('byredo','Byredo'),
  ('carolina-herrera','Carolina Herrera'),
  ('chanel','Chanel'),
  ('dior','Dior'),
  ('dolce-and-gabbana','Dolce & Gabbana'),
  ('giorgio-armani','Giorgio Armani'),
  ('gucci','Gucci'),
  ('initio','Initio'),
  ('jean-paul-gaultier','Jean Paul Gaultier'),
  ('jovoy','Jovoy'),
  ('le-labo','Le Labo'),
  ('loewe','Loewe'),
  ('maison-alhambra','Maison Alhambra'),
  ('mancera','Mancera'),
  ('montale','Montale'),
  ('montblanc','Montblanc'),
  ('narciso-rodriguez','Narciso Rodriguez'),
  ('parfums-de-marly','Parfums de Marly'),
  ('prada','Prada'),
  ('salvatore-ferragamo','Salvatore Ferragamo'),
  ('thomas-kosmala','Thomas Kosmala'),
  ('versace','Versace'),
  ('xerjoff','Xerjoff'),
  ('ysl','YSL')
on conflict do nothing;

-- PRODUCTS
insert into products(slug,name,brand_slug,category,gender,description,notes,longevity,sillage,is_niche,badge,hero_image,gallery) values
  ('narciso-rodriguez-for-her-edp','Narciso Rodriguez For Her EDP','narciso-rodriguez','Hoa cỏ xạ hương · Nữ','nu','Narciso Rodriguez For Her EDP — hoa cỏ xạ hương. Mở đầu hoa cam, hoa oải hương; trái tim hoa nhài, hoa hồng, xạ hương; lắng lại trên nền hoắc hương, hương bài, gỗ.','{"top": "Hoa cam, hoa oải hương", "mid": "Hoa nhài, hoa hồng, xạ hương", "base": "Hoắc hương, hương bài, gỗ"}',4,4,false,'Best seller','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-for-her-edp.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-for-her-edp.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-for-her-edp-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-for-her-edp-3.jpg"]'),
  ('narciso-rodriguez-for-her-edt','Narciso Rodriguez For Her EDT','narciso-rodriguez','Hoa cỏ xạ hương · Nữ','nu','Narciso Rodriguez For Her EDT — hoa cỏ xạ hương. Mở đầu hoa cam, bergamot; trái tim xạ hương, hoa nhài; lắng lại trên nền hoắc hương, gỗ, hương bài.','{"top": "Hoa cam, bergamot", "mid": "Xạ hương, hoa nhài", "base": "Hoắc hương, gỗ, hương bài"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-for-her-edt.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-for-her-edt.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-for-her-edt-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-for-her-edt-3.jpg"]'),
  ('narciso-rodriguez-rouge','Narciso Rodriguez Rouge','narciso-rodriguez','Hoa cỏ gỗ · Nữ','nu','Narciso Rodriguez Rouge — hoa cỏ gỗ. Mở đầu hồng tiêu, bergamot; trái tim hoa hồng, hoa nhài; lắng lại trên nền xạ hương, hoắc hương, gỗ.','{"top": "Hồng tiêu, bergamot", "mid": "Hoa hồng, hoa nhài", "base": "Xạ hương, hoắc hương, gỗ"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-rouge.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-rouge.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-rouge-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-rouge-3.jpg"]'),
  ('narciso-rodriguez-poudree','Narciso Rodriguez Poudrée','narciso-rodriguez','Hoa cỏ phấn xạ hương · Nữ','nu','Narciso Rodriguez Poudrée — hoa cỏ phấn xạ hương. Mở đầu hoa cam, hồng tiêu; trái tim hoa nhài, hoa hồng, xạ hương; lắng lại trên nền hoắc hương, đậu tonka, vani.','{"top": "Hoa cam, hồng tiêu", "mid": "Hoa nhài, hoa hồng, xạ hương", "base": "Hoắc hương, đậu tonka, vani"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-poudree.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-poudree.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-poudree-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-poudree-3.jpg"]'),
  ('narciso-rodriguez-musc-noir','Narciso Rodriguez Musc Noir','narciso-rodriguez','Hoa cỏ xạ hương ấm · Nữ','nu','Narciso Rodriguez Musc Noir — hoa cỏ xạ hương ấm. Mở đầu mận, hồng tiêu; trái tim xạ hương đen, hoa nhài; lắng lại trên nền hoắc hương, gỗ, vani.','{"top": "Mận, hồng tiêu", "mid": "Xạ hương đen, hoa nhài", "base": "Hoắc hương, gỗ, vani"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-musc-noir.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-musc-noir.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-musc-noir-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-musc-noir-3.jpg"]'),
  ('narciso-rodriguez-musc-noir-rose','Narciso Rodriguez Musc Noir Rose','narciso-rodriguez','Hoa hồng xạ hương · Nữ','nu','Narciso Rodriguez Musc Noir Rose — hoa hồng xạ hương. Mở đầu lê, hồng tiêu; trái tim hoa hồng, xạ hương; lắng lại trên nền hoắc hương, gỗ.','{"top": "Lê, hồng tiêu", "mid": "Hoa hồng, xạ hương", "base": "Hoắc hương, gỗ"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-musc-noir-rose.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-musc-noir-rose.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-musc-noir-rose-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-musc-noir-rose-3.jpg"]'),
  ('narciso-rodriguez-pure-musc','Narciso Rodriguez Pure Musc','narciso-rodriguez','Xạ hương sạch · Nữ','nu','Narciso Rodriguez Pure Musc — xạ hương sạch. Mở đầu hoa cam; trái tim xạ hương trắng, cashmeran; lắng lại trên nền gỗ trắng, xạ hương.','{"top": "Hoa cam", "mid": "Xạ hương trắng, cashmeran", "base": "Gỗ trắng, xạ hương"}',4,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-pure-musc.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-pure-musc.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-pure-musc-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-pure-musc-3.jpg"]'),
  ('narciso-rodriguez-fleur-musc','Narciso Rodriguez Fleur Musc','narciso-rodriguez','Hoa hồng xạ hương · Nữ','nu','Narciso Rodriguez Fleur Musc — hoa hồng xạ hương. Mở đầu hồng tiêu; trái tim hoa hồng, xạ hương; lắng lại trên nền hoắc hương, hổ phách.','{"top": "Hồng tiêu", "mid": "Hoa hồng, xạ hương", "base": "Hoắc hương, hổ phách"}',4,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-fleur-musc.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-fleur-musc.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-fleur-musc-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/narciso-rodriguez-fleur-musc-3.jpg"]'),
  ('gucci-flora-gorgeous-jasmine','Gucci Flora Gorgeous Jasmine','gucci','Hoa cỏ trắng · Nữ','nu','Gucci Flora Gorgeous Jasmine — hoa cỏ trắng. Mở đầu lê, hồng lựu; trái tim hoa nhài, cam bergamot; lắng lại trên nền xạ hương, gỗ.','{"top": "Lê, hồng lựu", "mid": "Hoa nhài, cam bergamot", "base": "Xạ hương, gỗ"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/gucci-flora-gorgeous-jasmine.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/gucci-flora-gorgeous-jasmine.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/gucci-flora-gorgeous-jasmine-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/gucci-flora-gorgeous-jasmine-3.jpg"]'),
  ('gucci-flora-gorgeous-gardenia','Gucci Flora Gorgeous Gardenia','gucci','Hoa cỏ ngọt · Nữ','nu','Gucci Flora Gorgeous Gardenia — hoa cỏ ngọt. Mở đầu lê, hồng lựu; trái tim hoa dành dành, hoa nhài; lắng lại trên nền đường nâu, hoắc hương.','{"top": "Lê, hồng lựu", "mid": "Hoa dành dành, hoa nhài", "base": "Đường nâu, hoắc hương"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/gucci-flora-gorgeous-gardenia.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/gucci-flora-gorgeous-gardenia.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/gucci-flora-gorgeous-gardenia-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/gucci-flora-gorgeous-gardenia-3.jpg"]'),
  ('gucci-bloom','Gucci Bloom','gucci','Hoa cỏ trắng · Nữ','nu','Gucci Bloom — hoa cỏ trắng. Mở đầu hoa nhài; trái tim hoa huệ tuberose, hoa nhài sambac; lắng lại trên nền rễ diên vĩ, xạ hương.','{"top": "Hoa nhài", "mid": "Hoa huệ tuberose, hoa nhài sambac", "base": "Rễ diên vĩ, xạ hương"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/gucci-bloom.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/gucci-bloom.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/gucci-bloom-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/gucci-bloom-3.jpg"]'),
  ('bleu-de-chanel-edp','Bleu de Chanel EDP','chanel','Hương gỗ thơm · Nam','nam','Bleu de Chanel EDP — hương gỗ thơm. Mở đầu bưởi, chanh, bạc hà; trái tim gừng, nhục đậu khấu, hoa nhài; lắng lại trên nền trầm hương, đàn hương, hương bài.','{"top": "Bưởi, chanh, bạc hà", "mid": "Gừng, nhục đậu khấu, hoa nhài", "base": "Trầm hương, đàn hương, hương bài"}',4,4,false,'Best seller','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/bleu-de-chanel-edp.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/bleu-de-chanel-edp.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/bleu-de-chanel-edp-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/bleu-de-chanel-edp-3.jpg"]'),
  ('dior-sauvage-edp','Dior Sauvage EDP','dior','Hương gỗ thơm · Nam','nam','Dior Sauvage EDP — hương gỗ thơm. Mở đầu cam bergamot, hồ tiêu; trái tim hoa oải hương, tiêu sichuan; lắng lại trên nền ambroxan, gỗ tuyết tùng.','{"top": "Cam bergamot, hồ tiêu", "mid": "Hoa oải hương, tiêu Sichuan", "base": "Ambroxan, gỗ tuyết tùng"}',4,4,false,'Best seller','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dior-sauvage-edp.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dior-sauvage-edp.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dior-sauvage-edp-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dior-sauvage-edp-3.jpg"]'),
  ('ysl-libre-edp','YSL Libre EDP','ysl','Hoa cỏ oải hương · Nữ','nu','YSL Libre EDP — hoa cỏ oải hương. Mở đầu quýt, bergamot; trái tim hoa oải hương, hoa cam, hoa nhài; lắng lại trên nền vani, xạ hương, tuyết tùng.','{"top": "Quýt, bergamot", "mid": "Hoa oải hương, hoa cam, hoa nhài", "base": "Vani, xạ hương, tuyết tùng"}',4,4,false,'Best seller','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/ysl-libre-edp.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/ysl-libre-edp.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/ysl-libre-edp-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/ysl-libre-edp-3.jpg"]'),
  ('ysl-y-edp','YSL Y EDP','ysl','Hương gỗ thơm · Nam','nam','YSL Y EDP — hương gỗ thơm. Mở đầu táo xanh, gừng, bergamot; trái tim xô thơm, hoa phong lữ; lắng lại trên nền gỗ tuyết tùng, hương bài, ambroxan.','{"top": "Táo xanh, gừng, bergamot", "mid": "Xô thơm, hoa phong lữ", "base": "Gỗ tuyết tùng, hương bài, ambroxan"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/ysl-y-edp.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/ysl-y-edp.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/ysl-y-edp-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/ysl-y-edp-3.jpg"]'),
  ('ysl-black-opium-edp','YSL Black Opium EDP','ysl','Phương Đông ngọt · Nữ','nu','YSL Black Opium EDP — phương đông ngọt. Mở đầu lê, hồng tiêu, cam; trái tim cà phê, hoa nhài; lắng lại trên nền vani, hoắc hương, tuyết tùng.','{"top": "Lê, hồng tiêu, cam", "mid": "Cà phê, hoa nhài", "base": "Vani, hoắc hương, tuyết tùng"}',4,4,false,'Best seller','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/ysl-black-opium-edp.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/ysl-black-opium-edp.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/ysl-black-opium-edp-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/ysl-black-opium-edp-3.jpg"]'),
  ('ysl-mon-paris-edp','YSL Mon Paris EDP','ysl','Hoa cỏ chypre trái cây · Nữ','nu','YSL Mon Paris EDP — hoa cỏ chypre trái cây. Mở đầu dâu tây, mâm xôi, quýt; trái tim hoa nhài, hoa vải; lắng lại trên nền hoắc hương, xạ hương trắng.','{"top": "Dâu tây, mâm xôi, quýt", "mid": "Hoa nhài, hoa vải", "base": "Hoắc hương, xạ hương trắng"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/ysl-mon-paris-edp.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/ysl-mon-paris-edp.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/ysl-mon-paris-edp-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/ysl-mon-paris-edp-3.jpg"]'),
  ('le-labo-another-13','Le Labo Another 13','le-labo','Hương xạ gỗ · Unisex · Niche','unisex','Le Labo Another 13 — hương xạ gỗ. Mở đầu trái cây amber, ambrox; trái tim xạ hương, hoa nhài; lắng lại trên nền hạt ambrette, rêu, long diên hương.','{"top": "Trái cây amber, ambrox", "mid": "Xạ hương, hoa nhài", "base": "Hạt ambrette, rêu, long diên hương"}',4,3,true,'Niche','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/le-labo-another-13.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/le-labo-another-13.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/le-labo-another-13-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/le-labo-another-13-3.jpg"]'),
  ('chanel-coco-mademoiselle-edp','Chanel Coco Mademoiselle EDP','chanel','Hoa cỏ Chypre · Nữ','nu','Chanel Coco Mademoiselle EDP — hoa cỏ chypre. Mở đầu cam, bergamot, quýt; trái tim hoa nhài, hoa hồng, vải; lắng lại trên nền hoắc hương, hương bài, xạ hương trắng.','{"top": "Cam, bergamot, quýt", "mid": "Hoa nhài, hoa hồng, vải", "base": "Hoắc hương, hương bài, xạ hương trắng"}',4,4,false,'Best seller','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-coco-mademoiselle-edp.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-coco-mademoiselle-edp.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-coco-mademoiselle-edp-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-coco-mademoiselle-edp-3.jpg"]'),
  ('chanel-n5-edp','Chanel N°5 EDP','chanel','Hoa cỏ aldehyde · Nữ','nu','Chanel N°5 EDP — hoa cỏ aldehyde. Mở đầu aldehyde, ylang-ylang, neroli; trái tim hoa hồng, hoa nhài, hoa iris; lắng lại trên nền đàn hương, hương bài, vani.','{"top": "Aldehyde, ylang-ylang, neroli", "mid": "Hoa hồng, hoa nhài, hoa iris", "base": "Đàn hương, hương bài, vani"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-n5-edp.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-n5-edp.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-n5-edp-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-n5-edp-3.jpg"]'),
  ('miss-dior-edp','Miss Dior EDP','dior','Hoa cỏ chypre · Nữ','nu','Miss Dior EDP — hoa cỏ chypre. Mở đầu cam bergamot, hồng tiêu; trái tim hoa hồng grasse, mẫu đơn; lắng lại trên nền đàn hương, xạ hương, hoắc hương.','{"top": "Cam bergamot, hồng tiêu", "mid": "Hoa hồng Grasse, mẫu đơn", "base": "Đàn hương, xạ hương, hoắc hương"}',4,4,false,'Best seller','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/miss-dior-edp.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/miss-dior-edp.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/miss-dior-edp-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/miss-dior-edp-3.jpg"]'),
  ('montblanc-signature','Montblanc Signature','montblanc','Hoa cỏ trái cây · Nữ','nu','Montblanc Signature — hoa cỏ trái cây. Mở đầu quýt, lê; trái tim hoa cam, hoa nhài; lắng lại trên nền xạ hương, gỗ đàn hương.','{"top": "Quýt, lê", "mid": "Hoa cam, hoa nhài", "base": "Xạ hương, gỗ đàn hương"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montblanc-signature.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montblanc-signature.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montblanc-signature-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montblanc-signature-3.jpg"]'),
  ('montblanc-legend-edt','Montblanc Legend EDT','montblanc','Hương fougère · Nam','nam','Montblanc Legend EDT — hương fougère. Mở đầu bergamot, oải hương, dứa; trái tim táo đỏ, hoa oải hương, hoa hồng; lắng lại trên nền rêu sồi, đàn hương, đậu tonka.','{"top": "Bergamot, oải hương, dứa", "mid": "Táo đỏ, hoa oải hương, hoa hồng", "base": "Rêu sồi, đàn hương, đậu tonka"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montblanc-legend-edt.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montblanc-legend-edt.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montblanc-legend-edt-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montblanc-legend-edt-3.jpg"]'),
  ('montblanc-explorer-edp','Montblanc Explorer EDP','montblanc','Hương gỗ thơm · Nam','nam','Montblanc Explorer EDP — hương gỗ thơm. Mở đầu bergamot ý, hồng tiêu; trái tim da thuộc, hoắc hương; lắng lại trên nền ambroxan, gỗ akigalawood.','{"top": "Bergamot Ý, hồng tiêu", "mid": "Da thuộc, hoắc hương", "base": "Ambroxan, gỗ akigalawood"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montblanc-explorer-edp.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montblanc-explorer-edp.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montblanc-explorer-edp-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montblanc-explorer-edp-3.jpg"]'),
  ('giorgio-armani-acqua-di-gio-edt','Giorgio Armani Acqua di Gio EDT','giorgio-armani','Hương thơm biển · Nam','nam','Giorgio Armani Acqua di Gio EDT — hương thơm biển. Mở đầu chanh, quýt, bergamot; trái tim hương biển, hoa nhài; lắng lại trên nền xạ hương trắng, tuyết tùng, hoắc hương.','{"top": "Chanh, quýt, bergamot", "mid": "Hương biển, hoa nhài", "base": "Xạ hương trắng, tuyết tùng, hoắc hương"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-acqua-di-gio-edt.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-acqua-di-gio-edt.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-acqua-di-gio-edt-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-acqua-di-gio-edt-3.jpg"]'),
  ('jean-paul-gaultier-le-male-edt','Jean Paul Gaultier Le Male EDT','jean-paul-gaultier','Hương fougère cay · Nam','nam','Jean Paul Gaultier Le Male EDT — hương fougère cay. Mở đầu bạc hà, oải hương, bergamot; trái tim quế, hoa cam; lắng lại trên nền vani, đậu tonka, hổ phách.','{"top": "Bạc hà, oải hương, bergamot", "mid": "Quế, hoa cam", "base": "Vani, đậu tonka, hổ phách"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jean-paul-gaultier-le-male-edt.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jean-paul-gaultier-le-male-edt.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jean-paul-gaultier-le-male-edt-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jean-paul-gaultier-le-male-edt-3.jpg"]'),
  ('jean-paul-gaultier-scandal-edp','Jean Paul Gaultier Scandal EDP','jean-paul-gaultier','Hoa cỏ ngọt gourmand · Nữ','nu','Jean Paul Gaultier Scandal EDP — hoa cỏ ngọt gourmand. Mở đầu cam máu, mật ong; trái tim hoa cam, hoa nhài; lắng lại trên nền hoắc hương, caramel, sáp ong.','{"top": "Cam máu, mật ong", "mid": "Hoa cam, hoa nhài", "base": "Hoắc hương, caramel, sáp ong"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jean-paul-gaultier-scandal-edp.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jean-paul-gaultier-scandal-edp.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jean-paul-gaultier-scandal-edp-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jean-paul-gaultier-scandal-edp-3.jpg"]'),
  ('burberry-her-edp','Burberry Her EDP','burberry','Hoa cỏ trái cây gourmand · Nữ','nu','Burberry Her EDP — hoa cỏ trái cây gourmand. Mở đầu quả mọng dại, mâm xôi đen; trái tim hoa violet, hoa nhài; lắng lại trên nền xạ hương, hoắc hương, hổ phách.','{"top": "Quả mọng dại, mâm xôi đen", "mid": "Hoa violet, hoa nhài", "base": "Xạ hương, hoắc hương, hổ phách"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/burberry-her-edp.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/burberry-her-edp.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/burberry-her-edp-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/burberry-her-edp-3.jpg"]'),
  ('byredo-la-tulipe','Byredo La Tulipe','byredo','Hoa cỏ tươi · Nữ · Niche','nu','Byredo La Tulipe — hoa cỏ tươi. Mở đầu lá tươi, hoa tulip; trái tim hoa hồng, hoa freesia; lắng lại trên nền vetiver, gỗ.','{"top": "Lá tươi, hoa tulip", "mid": "Hoa hồng, hoa freesia", "base": "Vetiver, gỗ"}',3,3,true,'Niche','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/byredo-la-tulipe.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/byredo-la-tulipe.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/byredo-la-tulipe-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/byredo-la-tulipe-3.jpg"]'),
  ('dolce-and-gabbana-the-one-edp','Dolce & Gabbana The One EDP','dolce-and-gabbana','Phương Đông hoa cỏ · Nữ','nu','Dolce & Gabbana The One EDP — phương đông hoa cỏ. Mở đầu bergamot, mandarin, lệ chi; trái tim hoa nhài, hoa huệ, mẫu đơn; lắng lại trên nền vani, hổ phách, xạ hương.','{"top": "Bergamot, mandarin, lệ chi", "mid": "Hoa nhài, hoa huệ, mẫu đơn", "base": "Vani, hổ phách, xạ hương"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dolce-and-gabbana-the-one-edp.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dolce-and-gabbana-the-one-edp.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dolce-and-gabbana-the-one-edp-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dolce-and-gabbana-the-one-edp-3.jpg"]'),
  ('prada-lhomme','Prada L''Homme','prada','Hương phấn hoa · Nam','nam','Prada L''Homme — hương phấn hoa. Mở đầu hạt mống, hồ tiêu, neroli; trái tim hoa iris, hoa violet, phong lữ; lắng lại trên nền tuyết tùng, đậu tonka, hoắc hương.','{"top": "Hạt mống, hồ tiêu, neroli", "mid": "Hoa iris, hoa violet, phong lữ", "base": "Tuyết tùng, đậu tonka, hoắc hương"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/prada-lhomme.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/prada-lhomme.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/prada-lhomme-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/prada-lhomme-3.jpg"]'),
  ('xerjoff-torino-21','Xerjoff Torino 21','xerjoff','Phương Đông gourmand · Unisex · Niche','unisex','Xerjoff Torino 21 — phương đông gourmand. Mở đầu rượu rum, quế; trái tim hoa cam, thuốc lá; lắng lại trên nền vani, gỗ, đậu tonka.','{"top": "Rượu rum, quế", "mid": "Hoa cam, thuốc lá", "base": "Vani, gỗ, đậu tonka"}',5,5,true,'Niche','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/xerjoff-torino-21.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/xerjoff-torino-21.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/xerjoff-torino-21-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/xerjoff-torino-21-3.jpg"]'),
  ('initio-oud-for-greatness','Initio Oud for Greatness','initio','Hương gỗ trầm cay · Unisex · Niche','unisex','Initio Oud for Greatness — hương gỗ trầm cay. Mở đầu nghệ tây, nhục đậu khấu; trái tim trầm hương oud, hoa oải hương; lắng lại trên nền xạ hương, hoắc hương, gỗ.','{"top": "Nghệ tây, nhục đậu khấu", "mid": "Trầm hương oud, hoa oải hương", "base": "Xạ hương, hoắc hương, gỗ"}',5,5,true,'Niche','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/initio-oud-for-greatness.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/initio-oud-for-greatness.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/initio-oud-for-greatness-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/initio-oud-for-greatness-3.jpg"]'),
  ('salvatore-ferragamo-signorina','Salvatore Ferragamo Signorina','salvatore-ferragamo','Hoa cỏ gourmand · Nữ','nu','Salvatore Ferragamo Signorina — hoa cỏ gourmand. Mở đầu lý chua đen, hồng tiêu; trái tim hoa mẫu đơn, hoa hồng; lắng lại trên nền panna cotta, hoắc hương, xạ hương.','{"top": "Lý chua đen, hồng tiêu", "mid": "Hoa mẫu đơn, hoa hồng", "base": "Panna cotta, hoắc hương, xạ hương"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/salvatore-ferragamo-signorina.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/salvatore-ferragamo-signorina.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/salvatore-ferragamo-signorina-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/salvatore-ferragamo-signorina-3.jpg"]'),
  ('loewe-aire','Loewe Aire','loewe','Hoa cỏ tươi · Nữ','nu','Loewe Aire — hoa cỏ tươi. Mở đầu bergamot, quýt; trái tim hoa nhài, hoa cam; lắng lại trên nền xạ hương, tuyết tùng.','{"top": "Bergamot, quýt", "mid": "Hoa nhài, hoa cam", "base": "Xạ hương, tuyết tùng"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/loewe-aire.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/loewe-aire.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/loewe-aire-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/loewe-aire-3.jpg"]'),
  ('maison-alhambra-amber-oud-ruby-edition','Maison Alhambra Amber Oud Ruby Edition','maison-alhambra','Phương Đông gỗ trầm · Unisex','unisex','Maison Alhambra Amber Oud Ruby Edition — phương đông gỗ trầm. Mở đầu táo, quả mọng; trái tim trầm hương oud, hoa hồng; lắng lại trên nền amber, xạ hương, gỗ.','{"top": "Táo, quả mọng", "mid": "Trầm hương oud, hoa hồng", "base": "Amber, xạ hương, gỗ"}',4,4,false,'Giá tốt','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-amber-oud-ruby-edition.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-amber-oud-ruby-edition.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-amber-oud-ruby-edition-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-amber-oud-ruby-edition-3.jpg"]'),
  ('maison-alhambra-delilah','Maison Alhambra Delilah','maison-alhambra','Hoa hồng trái cây · Nữ','nu','Maison Alhambra Delilah — hoa hồng trái cây. Mở đầu vải, đại hoàng; trái tim hoa hồng, mẫu đơn; lắng lại trên nền vani, xạ hương, tuyết tùng.','{"top": "Vải, đại hoàng", "mid": "Hoa hồng, mẫu đơn", "base": "Vani, xạ hương, tuyết tùng"}',4,4,false,'Giá tốt','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-delilah.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-delilah.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-delilah-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-delilah-3.jpg"]'),
  ('maison-alhambra-delilah-blanc','Maison Alhambra Delilah Blanc','maison-alhambra','Hoa cỏ trắng ngọt · Nữ','nu','Maison Alhambra Delilah Blanc — hoa cỏ trắng ngọt. Mở đầu lê, cam bergamot; trái tim hoa cam, hoa nhài; lắng lại trên nền vani, xạ hương, gỗ.','{"top": "Lê, cam bergamot", "mid": "Hoa cam, hoa nhài", "base": "Vani, xạ hương, gỗ"}',4,4,false,'Giá tốt','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-delilah-blanc.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-delilah-blanc.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-delilah-blanc-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-delilah-blanc-3.jpg"]'),
  ('maison-alhambra-delilah-rose','Maison Alhambra Delilah Rose','maison-alhambra','Hoa hồng ngọt · Nữ','nu','Maison Alhambra Delilah Rose — hoa hồng ngọt. Mở đầu quả mọng, bergamot; trái tim hoa hồng, mẫu đơn; lắng lại trên nền vani, hổ phách, xạ hương.','{"top": "Quả mọng, bergamot", "mid": "Hoa hồng, mẫu đơn", "base": "Vani, hổ phách, xạ hương"}',4,4,false,'Giá tốt','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-delilah-rose.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-delilah-rose.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-delilah-rose-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-delilah-rose-3.jpg"]'),
  ('maison-alhambra-musc-al-harair','Maison Alhambra Musc Al Harair','maison-alhambra','Xạ hương sạch · Unisex','unisex','Maison Alhambra Musc Al Harair — xạ hương sạch. Mở đầu hoa cam; trái tim xạ hương trắng, hoa nhài; lắng lại trên nền gỗ trắng, xạ hương.','{"top": "Hoa cam", "mid": "Xạ hương trắng, hoa nhài", "base": "Gỗ trắng, xạ hương"}',4,3,false,'Giá tốt','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-musc-al-harair.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-musc-al-harair.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-musc-al-harair-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-musc-al-harair-3.jpg"]'),
  ('maison-alhambra-kismet','Maison Alhambra Kismet','maison-alhambra','Phương Đông ngọt · Unisex','unisex','Maison Alhambra Kismet — phương đông ngọt. Mở đầu nghệ tây, hồng tiêu; trái tim hoa nhài, amber; lắng lại trên nền vani, gỗ, xạ hương.','{"top": "Nghệ tây, hồng tiêu", "mid": "Hoa nhài, amber", "base": "Vani, gỗ, xạ hương"}',4,4,false,'Giá tốt','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-kismet.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-kismet.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-kismet-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/maison-alhambra-kismet-3.jpg"]'),
  ('jovoy-les-jeux-sont-faits','Jovoy Les Jeux Sont Faits','jovoy','Hương gỗ da thuộc · Unisex · Niche','unisex','Jovoy Les Jeux Sont Faits — hương gỗ da thuộc. Mở đầu hồng tiêu, bergamot; trái tim da thuộc, hoa iris; lắng lại trên nền gỗ, hổ phách, hương bài.','{"top": "Hồng tiêu, bergamot", "mid": "Da thuộc, hoa iris", "base": "Gỗ, hổ phách, hương bài"}',4,4,true,'Niche','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jovoy-les-jeux-sont-faits.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jovoy-les-jeux-sont-faits.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jovoy-les-jeux-sont-faits-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jovoy-les-jeux-sont-faits-3.jpg"]'),
  ('montale-intense-cafe','Montale Intense Cafe','montale','Phương Đông gourmand · Unisex · Niche','unisex','Montale Intense Cafe — phương đông gourmand. Mở đầu cà phê, hoa hồng; trái tim hoa hồng, vani; lắng lại trên nền amber, xạ hương, gỗ.','{"top": "Cà phê, hoa hồng", "mid": "Hoa hồng, vani", "base": "Amber, xạ hương, gỗ"}',5,5,true,'Niche','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montale-intense-cafe.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montale-intense-cafe.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montale-intense-cafe-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montale-intense-cafe-3.jpg"]'),
  ('mancera-cedrat-boise','Mancera Cedrat Boise','mancera','Hương gỗ cam chanh · Unisex · Niche','unisex','Mancera Cedrat Boise — hương gỗ cam chanh. Mở đầu chanh, bergamot, cam; trái tim hoa nhài, gia vị; lắng lại trên nền gỗ, hoắc hương, xạ hương.','{"top": "Chanh, bergamot, cam", "mid": "Hoa nhài, gia vị", "base": "Gỗ, hoắc hương, xạ hương"}',4,5,true,'Niche','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/mancera-cedrat-boise.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/mancera-cedrat-boise.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/mancera-cedrat-boise-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/mancera-cedrat-boise-3.jpg"]'),
  ('armaf-club-de-nuit-intense-man','Armaf Club de Nuit Intense Man','armaf','Hương gỗ trái cây · Nam','nam','Armaf Club de Nuit Intense Man — hương gỗ trái cây. Mở đầu dứa, chanh, cam bergamot; trái tim hoa nhài, hồng, bạch dương; lắng lại trên nền xạ hương, rêu sồi, vani.','{"top": "Dứa, chanh, cam bergamot", "mid": "Hoa nhài, hồng, bạch dương", "base": "Xạ hương, rêu sồi, vani"}',4,5,false,'Giá tốt','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/armaf-club-de-nuit-intense-man.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/armaf-club-de-nuit-intense-man.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/armaf-club-de-nuit-intense-man-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/armaf-club-de-nuit-intense-man-3.jpg"]'),
  ('chanel-chance-edt','Chanel Chance EDT','chanel','Hoa cỏ chypre · Nữ','nu','Chanel Chance EDT — hoa cỏ chypre. Mở đầu hồng tiêu, chanh vàng; trái tim hoa nhài, hoa dành dành; lắng lại trên nền hoắc hương, hương bài, xạ hương.','{"top": "Hồng tiêu, chanh vàng", "mid": "Hoa nhài, hoa dành dành", "base": "Hoắc hương, hương bài, xạ hương"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-chance-edt.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-chance-edt.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-chance-edt-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-chance-edt-3.jpg"]'),
  ('chanel-chance-eau-fraiche','Chanel Chance Eau Fraîche','chanel','Hoa cỏ tươi · Nữ','nu','Chanel Chance Eau Fraîche — hoa cỏ tươi. Mở đầu chanh vàng, bưởi; trái tim hoa nhài, hoa dành dành; lắng lại trên nền hoắc hương, vetiver, tuyết tùng.','{"top": "Chanh vàng, bưởi", "mid": "Hoa nhài, hoa dành dành", "base": "Hoắc hương, vetiver, tuyết tùng"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-chance-eau-fraiche.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-chance-eau-fraiche.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-chance-eau-fraiche-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-chance-eau-fraiche-3.jpg"]'),
  ('versace-pour-homme','Versace Pour Homme','versace','Hương thơm biển gỗ · Nam','nam','Versace Pour Homme — hương thơm biển gỗ. Mở đầu bergamot, neroli, chanh; trái tim cỏ hương bài, phong lữ, xô thơm; lắng lại trên nền xạ hương, tuyết tùng, hương bài.','{"top": "Bergamot, neroli, chanh", "mid": "Cỏ hương bài, phong lữ, xô thơm", "base": "Xạ hương, tuyết tùng, hương bài"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/versace-pour-homme.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/versace-pour-homme.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/versace-pour-homme-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/versace-pour-homme-3.jpg"]'),
  ('parfums-de-marly-valaya','Parfums de Marly Valaya','parfums-de-marly','Hoa cỏ xạ hương · Nữ · Niche','nu','Parfums de Marly Valaya — hoa cỏ xạ hương. Mở đầu lê, hồng tiêu; trái tim hoa nhài, hoa cam; lắng lại trên nền xạ hương trắng, vani, gỗ.','{"top": "Lê, hồng tiêu", "mid": "Hoa nhài, hoa cam", "base": "Xạ hương trắng, vani, gỗ"}',4,4,true,'Niche','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/parfums-de-marly-valaya.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/parfums-de-marly-valaya.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/parfums-de-marly-valaya-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/parfums-de-marly-valaya-3.jpg"]'),
  ('parfums-de-marly-delina','Parfums de Marly Delina','parfums-de-marly','Hoa hồng trái cây · Nữ · Niche','nu','Parfums de Marly Delina — hoa hồng trái cây. Mở đầu vải, đại hoàng, bergamot; trái tim hoa hồng thổ, mẫu đơn, linh lan; lắng lại trên nền xạ hương, vani, tuyết tùng.','{"top": "Vải, đại hoàng, bergamot", "mid": "Hoa hồng Thổ, mẫu đơn, linh lan", "base": "Xạ hương, vani, tuyết tùng"}',4,4,true,'Best seller','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/parfums-de-marly-delina.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/parfums-de-marly-delina.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/parfums-de-marly-delina-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/parfums-de-marly-delina-3.jpg"]'),
  ('dolce-and-gabbana-light-blue-edt','Dolce & Gabbana Light Blue EDT','dolce-and-gabbana','Hoa cỏ trái cây · Nữ','nu','Dolce & Gabbana Light Blue EDT — hoa cỏ trái cây. Mở đầu táo granny smith, chanh; trái tim hoa nhài, tre trúc, hoa hồng trắng; lắng lại trên nền tuyết tùng, xạ hương, hổ phách.','{"top": "Táo Granny Smith, chanh", "mid": "Hoa nhài, tre trúc, hoa hồng trắng", "base": "Tuyết tùng, xạ hương, hổ phách"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dolce-and-gabbana-light-blue-edt.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dolce-and-gabbana-light-blue-edt.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dolce-and-gabbana-light-blue-edt-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dolce-and-gabbana-light-blue-edt-3.jpg"]'),
  ('giorgio-armani-acqua-di-gioia','Giorgio Armani Acqua di Gioia','giorgio-armani','Hương thơm biển · Nữ','nu','Giorgio Armani Acqua di Gioia — hương thơm biển. Mở đầu chanh, bạc hà; trái tim hoa nhài, hương biển; lắng lại trên nền tuyết tùng, đường nâu, xạ hương.','{"top": "Chanh, bạc hà", "mid": "Hoa nhài, hương biển", "base": "Tuyết tùng, đường nâu, xạ hương"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-acqua-di-gioia.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-acqua-di-gioia.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-acqua-di-gioia-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-acqua-di-gioia-3.jpg"]'),
  ('giorgio-armani-acqua-di-gio-profondo','Giorgio Armani Acqua di Gio Profondo','giorgio-armani','Hương thơm biển gỗ · Nam','nam','Giorgio Armani Acqua di Gio Profondo — hương thơm biển gỗ. Mở đầu hương biển, bergamot, chanh; trái tim hương nước, hoắc hương, hồng hương; lắng lại trên nền xạ hương, ambroxan, gỗ.','{"top": "Hương biển, bergamot, chanh", "mid": "Hương nước, hoắc hương, hồng hương", "base": "Xạ hương, ambroxan, gỗ"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-acqua-di-gio-profondo.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-acqua-di-gio-profondo.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-acqua-di-gio-profondo-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-acqua-di-gio-profondo-3.jpg"]'),
  ('prada-paradoxe','Prada Paradoxe','prada','Hoa cỏ xạ hương · Nữ','nu','Prada Paradoxe — hoa cỏ xạ hương. Mở đầu bergamot, hồng tiêu; trái tim hoa nhài neroli; lắng lại trên nền xạ hương trắng, hương amber.','{"top": "Bergamot, hồng tiêu", "mid": "Hoa nhài neroli", "base": "Xạ hương trắng, hương amber"}',4,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/prada-paradoxe.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/prada-paradoxe.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/prada-paradoxe-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/prada-paradoxe-3.jpg"]'),
  ('versace-eros-edt','Versace Eros EDT','versace','Phương Đông tươi · Nam','nam','Versace Eros EDT — phương đông tươi. Mở đầu bạc hà, táo xanh, chanh; trái tim đậu tonka, ambroxan, phong lữ; lắng lại trên nền vani, hương bài, tuyết tùng.','{"top": "Bạc hà, táo xanh, chanh", "mid": "Đậu tonka, ambroxan, phong lữ", "base": "Vani, hương bài, tuyết tùng"}',4,4,false,'Best seller','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/versace-eros-edt.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/versace-eros-edt.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/versace-eros-edt-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/versace-eros-edt-3.jpg"]'),
  ('jean-paul-gaultier-le-male-le-parfum','Jean Paul Gaultier Le Male Le Parfum','jean-paul-gaultier','Phương Đông ambery · Nam','nam','Jean Paul Gaultier Le Male Le Parfum — phương đông ambery. Mở đầu bạc hà, bạch đậu khấu; trái tim hoa oải hương, iris; lắng lại trên nền vani, amber, đậu tonka.','{"top": "Bạc hà, bạch đậu khấu", "mid": "Hoa oải hương, iris", "base": "Vani, amber, đậu tonka"}',5,5,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jean-paul-gaultier-le-male-le-parfum.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jean-paul-gaultier-le-male-le-parfum.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jean-paul-gaultier-le-male-le-parfum-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jean-paul-gaultier-le-male-le-parfum-3.jpg"]'),
  ('jean-paul-gaultier-divine','Jean Paul Gaultier Divine','jean-paul-gaultier','Hoa cỏ trắng gourmand · Nữ','nu','Jean Paul Gaultier Divine — hoa cỏ trắng gourmand. Mở đầu bergamot, lê; trái tim hoa huệ, kem tươi; lắng lại trên nền xạ hương, gỗ, meringue.','{"top": "Bergamot, lê", "mid": "Hoa huệ, kem tươi", "base": "Xạ hương, gỗ, meringue"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jean-paul-gaultier-divine.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jean-paul-gaultier-divine.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jean-paul-gaultier-divine-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/jean-paul-gaultier-divine-3.jpg"]'),
  ('dior-sauvage-elixir','Dior Sauvage Elixir','dior','Phương Đông cay gỗ · Nam','nam','Dior Sauvage Elixir — phương đông cay gỗ. Mở đầu quế, nhục đậu khấu, bưởi; trái tim hoa oải hương, cam thảo; lắng lại trên nền trầm hương, đàn hương, hương bài.','{"top": "Quế, nhục đậu khấu, bưởi", "mid": "Hoa oải hương, cam thảo", "base": "Trầm hương, đàn hương, hương bài"}',5,5,false,'Hot','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dior-sauvage-elixir.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dior-sauvage-elixir.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dior-sauvage-elixir-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dior-sauvage-elixir-3.jpg"]'),
  ('dior-addict-edp','Dior Addict EDP','dior','Hoa cỏ phương Đông · Nữ','nu','Dior Addict EDP — hoa cỏ phương đông. Mở đầu hoa nhài sambac, bergamot; trái tim hoa huệ, hoa cam; lắng lại trên nền vani bourbon, đậu tonka, gỗ.','{"top": "Hoa nhài sambac, bergamot", "mid": "Hoa huệ, hoa cam", "base": "Vani bourbon, đậu tonka, gỗ"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dior-addict-edp.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dior-addict-edp.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dior-addict-edp-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/dior-addict-edp-3.jpg"]'),
  ('thomas-kosmala-no-4-apres-lamour','Thomas Kosmala No. 4 Après l''Amour','thomas-kosmala','Hoa cỏ xạ hương · Unisex · Niche','unisex','Thomas Kosmala No. 4 Après l''Amour — hoa cỏ xạ hương. Mở đầu bergamot, gừng; trái tim hoa cam, hoa nhài; lắng lại trên nền xạ hương, gỗ đàn hương, hổ phách.','{"top": "Bergamot, gừng", "mid": "Hoa cam, hoa nhài", "base": "Xạ hương, gỗ đàn hương, hổ phách"}',4,4,true,'Niche','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/thomas-kosmala-no-4-apres-lamour.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/thomas-kosmala-no-4-apres-lamour.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/thomas-kosmala-no-4-apres-lamour-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/thomas-kosmala-no-4-apres-lamour-3.jpg"]'),
  ('afnan-9pm','Afnan 9PM','afnan','Phương Đông ngọt · Nam','nam','Afnan 9PM — phương đông ngọt. Mở đầu táo, quế, oải hương; trái tim hoa cam, hạnh nhân; lắng lại trên nền vani, đậu tonka, amber.','{"top": "Táo, quế, oải hương", "mid": "Hoa cam, hạnh nhân", "base": "Vani, đậu tonka, amber"}',4,4,false,'Giá tốt','https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/afnan-9pm.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/afnan-9pm.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/afnan-9pm-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/afnan-9pm-3.jpg"]'),
  ('montblanc-explorer-ultra-blue','Montblanc Explorer Ultra Blue','montblanc','Hương thơm biển gỗ · Nam','nam','Montblanc Explorer Ultra Blue — hương thơm biển gỗ. Mở đầu chanh, bạc hà, dứa; trái tim muối biển, hoa oải hương; lắng lại trên nền ambroxan, gỗ, hoắc hương.','{"top": "Chanh, bạc hà, dứa", "mid": "Muối biển, hoa oải hương", "base": "Ambroxan, gỗ, hoắc hương"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montblanc-explorer-ultra-blue.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montblanc-explorer-ultra-blue.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montblanc-explorer-ultra-blue-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/montblanc-explorer-ultra-blue-3.jpg"]'),
  ('chanel-allure-homme-sport-edt','Chanel Allure Homme Sport EDT','chanel','Hương gỗ thơm · Nam','nam','Chanel Allure Homme Sport EDT — hương gỗ thơm. Mở đầu cam, quýt, hồ tiêu; trái tim tiêu, hoa cam neroli; lắng lại trên nền xạ hương trắng, tuyết tùng, hương bài.','{"top": "Cam, quýt, hồ tiêu", "mid": "Tiêu, hoa cam neroli", "base": "Xạ hương trắng, tuyết tùng, hương bài"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-allure-homme-sport-edt.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-allure-homme-sport-edt.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-allure-homme-sport-edt-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/chanel-allure-homme-sport-edt-3.jpg"]'),
  ('carolina-herrera-212-men-sexy','Carolina Herrera 212 Men Sexy','carolina-herrera','Phương Đông cay · Nam','nam','Carolina Herrera 212 Men Sexy — phương đông cay. Mở đầu bạc hà, bergamot, gừng; trái tim hoa oải hương, hồng tiêu; lắng lại trên nền vani, gỗ đàn hương, xạ hương.','{"top": "Bạc hà, bergamot, gừng", "mid": "Hoa oải hương, hồng tiêu", "base": "Vani, gỗ đàn hương, xạ hương"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/carolina-herrera-212-men-sexy.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/carolina-herrera-212-men-sexy.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/carolina-herrera-212-men-sexy-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/carolina-herrera-212-men-sexy-3.jpg"]'),
  ('miss-dior-blooming-bouquet','Miss Dior Blooming Bouquet','dior','Hoa cỏ tươi · Nữ','nu','Miss Dior Blooming Bouquet — hoa cỏ tươi. Mở đầu cam sicily, quả vải; trái tim hoa mẫu đơn, hoa hồng; lắng lại trên nền xạ hương trắng.','{"top": "Cam Sicily, quả vải", "mid": "Hoa mẫu đơn, hoa hồng", "base": "Xạ hương trắng"}',3,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/miss-dior-blooming-bouquet.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/miss-dior-blooming-bouquet.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/miss-dior-blooming-bouquet-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/miss-dior-blooming-bouquet-3.jpg"]'),
  ('giorgio-armani-my-way-edp','Giorgio Armani My Way EDP','giorgio-armani','Hoa cỏ trắng · Nữ','nu','Giorgio Armani My Way EDP — hoa cỏ trắng. Mở đầu bergamot, hoa cam; trái tim hoa huệ, hoa nhài ấn độ; lắng lại trên nền tuyết tùng, xạ hương, vani.','{"top": "Bergamot, hoa cam", "mid": "Hoa huệ, hoa nhài Ấn Độ", "base": "Tuyết tùng, xạ hương, vani"}',4,3,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-my-way-edp.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-my-way-edp.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-my-way-edp-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-my-way-edp-3.jpg"]'),
  ('giorgio-armani-si-passione','Giorgio Armani Sì Passione','giorgio-armani','Hoa cỏ trái cây · Nữ','nu','Giorgio Armani Sì Passione — hoa cỏ trái cây. Mở đầu lê, hồng tiêu; trái tim hoa hồng, hoa nhài, hoa huệ; lắng lại trên nền vani, gỗ tuyết tùng, hoắc hương.','{"top": "Lê, hồng tiêu", "mid": "Hoa hồng, hoa nhài, hoa huệ", "base": "Vani, gỗ tuyết tùng, hoắc hương"}',4,4,false,null,'https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-si-passione.jpg','["https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-si-passione.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-si-passione-2.jpg", "https://bekajgoeqyrfrekfplho.supabase.co/storage/v1/object/public/products/giorgio-armani-si-passione-3.jpg"]')
on conflict (slug) do nothing;

-- VARIANTS (Chiết 5ml, Chiết 10ml, Full)
insert into product_variants(product_slug,kind,label,volume_ml,price,sort) values
  ('narciso-rodriguez-for-her-edp','chiet','Chiết 5ml',5,200000,1),
  ('narciso-rodriguez-for-her-edp','chiet','Chiết 10ml',10,340000,2),
  ('narciso-rodriguez-for-her-edp','full','Full 100ml',100,2690000,3),
  ('narciso-rodriguez-for-her-edt','chiet','Chiết 5ml',5,190000,1),
  ('narciso-rodriguez-for-her-edt','chiet','Chiết 10ml',10,320000,2),
  ('narciso-rodriguez-for-her-edt','full','Full 100ml',100,2490000,3),
  ('narciso-rodriguez-rouge','chiet','Chiết 5ml',5,210000,1),
  ('narciso-rodriguez-rouge','chiet','Chiết 10ml',10,350000,2),
  ('narciso-rodriguez-rouge','full','Full 100ml',100,2790000,3),
  ('narciso-rodriguez-poudree','chiet','Chiết 5ml',5,210000,1),
  ('narciso-rodriguez-poudree','chiet','Chiết 10ml',10,350000,2),
  ('narciso-rodriguez-poudree','full','Full 100ml',100,2790000,3),
  ('narciso-rodriguez-musc-noir','chiet','Chiết 5ml',5,210000,1),
  ('narciso-rodriguez-musc-noir','chiet','Chiết 10ml',10,360000,2),
  ('narciso-rodriguez-musc-noir','full','Full 90ml',90,2890000,3),
  ('narciso-rodriguez-musc-noir-rose','chiet','Chiết 5ml',5,210000,1),
  ('narciso-rodriguez-musc-noir-rose','chiet','Chiết 10ml',10,360000,2),
  ('narciso-rodriguez-musc-noir-rose','full','Full 90ml',90,2890000,3),
  ('narciso-rodriguez-pure-musc','chiet','Chiết 5ml',5,200000,1),
  ('narciso-rodriguez-pure-musc','chiet','Chiết 10ml',10,340000,2),
  ('narciso-rodriguez-pure-musc','full','Full 100ml',100,2690000,3),
  ('narciso-rodriguez-fleur-musc','chiet','Chiết 5ml',5,200000,1),
  ('narciso-rodriguez-fleur-musc','chiet','Chiết 10ml',10,340000,2),
  ('narciso-rodriguez-fleur-musc','full','Full 100ml',100,2690000,3),
  ('gucci-flora-gorgeous-jasmine','chiet','Chiết 5ml',5,200000,1),
  ('gucci-flora-gorgeous-jasmine','chiet','Chiết 10ml',10,330000,2),
  ('gucci-flora-gorgeous-jasmine','full','Full 100ml',100,2590000,3),
  ('gucci-flora-gorgeous-gardenia','chiet','Chiết 5ml',5,200000,1),
  ('gucci-flora-gorgeous-gardenia','chiet','Chiết 10ml',10,340000,2),
  ('gucci-flora-gorgeous-gardenia','full','Full 100ml',100,2690000,3),
  ('gucci-bloom','chiet','Chiết 5ml',5,200000,1),
  ('gucci-bloom','chiet','Chiết 10ml',10,340000,2),
  ('gucci-bloom','full','Full 100ml',100,2690000,3),
  ('bleu-de-chanel-edp','chiet','Chiết 5ml',5,250000,1),
  ('bleu-de-chanel-edp','chiet','Chiết 10ml',10,420000,2),
  ('bleu-de-chanel-edp','full','Full 100ml',100,3690000,3),
  ('dior-sauvage-edp','chiet','Chiết 5ml',5,220000,1),
  ('dior-sauvage-edp','chiet','Chiết 10ml',10,380000,2),
  ('dior-sauvage-edp','full','Full 100ml',100,3190000,3),
  ('ysl-libre-edp','chiet','Chiết 5ml',5,220000,1),
  ('ysl-libre-edp','chiet','Chiết 10ml',10,380000,2),
  ('ysl-libre-edp','full','Full 90ml',90,2990000,3),
  ('ysl-y-edp','chiet','Chiết 5ml',5,200000,1),
  ('ysl-y-edp','chiet','Chiết 10ml',10,340000,2),
  ('ysl-y-edp','full','Full 100ml',100,2790000,3),
  ('ysl-black-opium-edp','chiet','Chiết 5ml',5,220000,1),
  ('ysl-black-opium-edp','chiet','Chiết 10ml',10,370000,2),
  ('ysl-black-opium-edp','full','Full 90ml',90,2890000,3),
  ('ysl-mon-paris-edp','chiet','Chiết 5ml',5,210000,1),
  ('ysl-mon-paris-edp','chiet','Chiết 10ml',10,360000,2),
  ('ysl-mon-paris-edp','full','Full 90ml',90,2790000,3),
  ('le-labo-another-13','chiet','Chiết 5ml',5,340000,1),
  ('le-labo-another-13','chiet','Chiết 10ml',10,560000,2),
  ('le-labo-another-13','full','Full 100ml',100,6790000,3),
  ('chanel-coco-mademoiselle-edp','chiet','Chiết 5ml',5,250000,1),
  ('chanel-coco-mademoiselle-edp','chiet','Chiết 10ml',10,420000,2),
  ('chanel-coco-mademoiselle-edp','full','Full 100ml',100,3690000,3),
  ('chanel-n5-edp','chiet','Chiết 5ml',5,250000,1),
  ('chanel-n5-edp','chiet','Chiết 10ml',10,430000,2),
  ('chanel-n5-edp','full','Full 100ml',100,3790000,3),
  ('miss-dior-edp','chiet','Chiết 5ml',5,220000,1),
  ('miss-dior-edp','chiet','Chiết 10ml',10,380000,2),
  ('miss-dior-edp','full','Full 100ml',100,3190000,3),
  ('montblanc-signature','chiet','Chiết 5ml',5,150000,1),
  ('montblanc-signature','chiet','Chiết 10ml',10,250000,2),
  ('montblanc-signature','full','Full 90ml',90,1690000,3),
  ('montblanc-legend-edt','chiet','Chiết 5ml',5,150000,1),
  ('montblanc-legend-edt','chiet','Chiết 10ml',10,240000,2),
  ('montblanc-legend-edt','full','Full 100ml',100,1590000,3),
  ('montblanc-explorer-edp','chiet','Chiết 5ml',5,160000,1),
  ('montblanc-explorer-edp','chiet','Chiết 10ml',10,260000,2),
  ('montblanc-explorer-edp','full','Full 100ml',100,1890000,3),
  ('giorgio-armani-acqua-di-gio-edt','chiet','Chiết 5ml',5,160000,1),
  ('giorgio-armani-acqua-di-gio-edt','chiet','Chiết 10ml',10,260000,2),
  ('giorgio-armani-acqua-di-gio-edt','full','Full 100ml',100,1990000,3),
  ('jean-paul-gaultier-le-male-edt','chiet','Chiết 5ml',5,170000,1),
  ('jean-paul-gaultier-le-male-edt','chiet','Chiết 10ml',10,280000,2),
  ('jean-paul-gaultier-le-male-edt','full','Full 125ml',125,1990000,3),
  ('jean-paul-gaultier-scandal-edp','chiet','Chiết 5ml',5,190000,1),
  ('jean-paul-gaultier-scandal-edp','chiet','Chiết 10ml',10,310000,2),
  ('jean-paul-gaultier-scandal-edp','full','Full 80ml',80,2390000,3),
  ('burberry-her-edp','chiet','Chiết 5ml',5,190000,1),
  ('burberry-her-edp','chiet','Chiết 10ml',10,320000,2),
  ('burberry-her-edp','full','Full 100ml',100,2490000,3),
  ('byredo-la-tulipe','chiet','Chiết 5ml',5,310000,1),
  ('byredo-la-tulipe','chiet','Chiết 10ml',10,520000,2),
  ('byredo-la-tulipe','full','Full 100ml',100,6490000,3),
  ('dolce-and-gabbana-the-one-edp','chiet','Chiết 5ml',5,190000,1),
  ('dolce-and-gabbana-the-one-edp','chiet','Chiết 10ml',10,320000,2),
  ('dolce-and-gabbana-the-one-edp','full','Full 75ml',75,2490000,3),
  ('prada-lhomme','chiet','Chiết 5ml',5,180000,1),
  ('prada-lhomme','chiet','Chiết 10ml',10,300000,2),
  ('prada-lhomme','full','Full 100ml',100,2390000,3),
  ('xerjoff-torino-21','chiet','Chiết 5ml',5,460000,1),
  ('xerjoff-torino-21','chiet','Chiết 10ml',10,780000,2),
  ('xerjoff-torino-21','full','Full 100ml',100,9990000,3),
  ('initio-oud-for-greatness','chiet','Chiết 5ml',5,420000,1),
  ('initio-oud-for-greatness','chiet','Chiết 10ml',10,700000,2),
  ('initio-oud-for-greatness','full','Full 90ml',90,7990000,3),
  ('salvatore-ferragamo-signorina','chiet','Chiết 5ml',5,150000,1),
  ('salvatore-ferragamo-signorina','chiet','Chiết 10ml',10,250000,2),
  ('salvatore-ferragamo-signorina','full','Full 100ml',100,1790000,3),
  ('loewe-aire','chiet','Chiết 5ml',5,190000,1),
  ('loewe-aire','chiet','Chiết 10ml',10,320000,2),
  ('loewe-aire','full','Full 100ml',100,2490000,3),
  ('maison-alhambra-amber-oud-ruby-edition','chiet','Chiết 5ml',5,70000,1),
  ('maison-alhambra-amber-oud-ruby-edition','chiet','Chiết 10ml',10,110000,2),
  ('maison-alhambra-amber-oud-ruby-edition','full','Full 100ml',100,690000,3),
  ('maison-alhambra-delilah','chiet','Chiết 5ml',5,70000,1),
  ('maison-alhambra-delilah','chiet','Chiết 10ml',10,110000,2),
  ('maison-alhambra-delilah','full','Full 100ml',100,690000,3),
  ('maison-alhambra-delilah-blanc','chiet','Chiết 5ml',5,70000,1),
  ('maison-alhambra-delilah-blanc','chiet','Chiết 10ml',10,110000,2),
  ('maison-alhambra-delilah-blanc','full','Full 100ml',100,690000,3),
  ('maison-alhambra-delilah-rose','chiet','Chiết 5ml',5,70000,1),
  ('maison-alhambra-delilah-rose','chiet','Chiết 10ml',10,110000,2),
  ('maison-alhambra-delilah-rose','full','Full 100ml',100,690000,3),
  ('maison-alhambra-musc-al-harair','chiet','Chiết 5ml',5,65000,1),
  ('maison-alhambra-musc-al-harair','chiet','Chiết 10ml',10,100000,2),
  ('maison-alhambra-musc-al-harair','full','Full 100ml',100,650000,3),
  ('maison-alhambra-kismet','chiet','Chiết 5ml',5,70000,1),
  ('maison-alhambra-kismet','chiet','Chiết 10ml',10,110000,2),
  ('maison-alhambra-kismet','full','Full 100ml',100,690000,3),
  ('jovoy-les-jeux-sont-faits','chiet','Chiết 5ml',5,290000,1),
  ('jovoy-les-jeux-sont-faits','chiet','Chiết 10ml',10,480000,2),
  ('jovoy-les-jeux-sont-faits','full','Full 100ml',100,5490000,3),
  ('montale-intense-cafe','chiet','Chiết 5ml',5,250000,1),
  ('montale-intense-cafe','chiet','Chiết 10ml',10,420000,2),
  ('montale-intense-cafe','full','Full 100ml',100,3990000,3),
  ('mancera-cedrat-boise','chiet','Chiết 5ml',5,250000,1),
  ('mancera-cedrat-boise','chiet','Chiết 10ml',10,420000,2),
  ('mancera-cedrat-boise','full','Full 120ml',120,3990000,3),
  ('armaf-club-de-nuit-intense-man','chiet','Chiết 5ml',5,110000,1),
  ('armaf-club-de-nuit-intense-man','chiet','Chiết 10ml',10,180000,2),
  ('armaf-club-de-nuit-intense-man','full','Full 105ml',105,1190000,3),
  ('chanel-chance-edt','chiet','Chiết 5ml',5,220000,1),
  ('chanel-chance-edt','chiet','Chiết 10ml',10,380000,2),
  ('chanel-chance-edt','full','Full 100ml',100,3290000,3),
  ('chanel-chance-eau-fraiche','chiet','Chiết 5ml',5,220000,1),
  ('chanel-chance-eau-fraiche','chiet','Chiết 10ml',10,380000,2),
  ('chanel-chance-eau-fraiche','full','Full 100ml',100,3290000,3),
  ('versace-pour-homme','chiet','Chiết 5ml',5,160000,1),
  ('versace-pour-homme','chiet','Chiết 10ml',10,260000,2),
  ('versace-pour-homme','full','Full 100ml',100,1890000,3),
  ('parfums-de-marly-valaya','chiet','Chiết 5ml',5,370000,1),
  ('parfums-de-marly-valaya','chiet','Chiết 10ml',10,620000,2),
  ('parfums-de-marly-valaya','full','Full 75ml',75,6990000,3),
  ('parfums-de-marly-delina','chiet','Chiết 5ml',5,370000,1),
  ('parfums-de-marly-delina','chiet','Chiết 10ml',10,620000,2),
  ('parfums-de-marly-delina','full','Full 75ml',75,6990000,3),
  ('dolce-and-gabbana-light-blue-edt','chiet','Chiết 5ml',5,160000,1),
  ('dolce-and-gabbana-light-blue-edt','chiet','Chiết 10ml',10,260000,2),
  ('dolce-and-gabbana-light-blue-edt','full','Full 100ml',100,1890000,3),
  ('giorgio-armani-acqua-di-gioia','chiet','Chiết 5ml',5,170000,1),
  ('giorgio-armani-acqua-di-gioia','chiet','Chiết 10ml',10,290000,2),
  ('giorgio-armani-acqua-di-gioia','full','Full 100ml',100,2190000,3),
  ('giorgio-armani-acqua-di-gio-profondo','chiet','Chiết 5ml',5,190000,1),
  ('giorgio-armani-acqua-di-gio-profondo','chiet','Chiết 10ml',10,320000,2),
  ('giorgio-armani-acqua-di-gio-profondo','full','Full 100ml',100,2490000,3),
  ('prada-paradoxe','chiet','Chiết 5ml',5,210000,1),
  ('prada-paradoxe','chiet','Chiết 10ml',10,350000,2),
  ('prada-paradoxe','full','Full 90ml',90,2790000,3),
  ('versace-eros-edt','chiet','Chiết 5ml',5,170000,1),
  ('versace-eros-edt','chiet','Chiết 10ml',10,280000,2),
  ('versace-eros-edt','full','Full 100ml',100,1890000,3),
  ('jean-paul-gaultier-le-male-le-parfum','chiet','Chiết 5ml',5,200000,1),
  ('jean-paul-gaultier-le-male-le-parfum','chiet','Chiết 10ml',10,340000,2),
  ('jean-paul-gaultier-le-male-le-parfum','full','Full 125ml',125,2590000,3),
  ('jean-paul-gaultier-divine','chiet','Chiết 5ml',5,200000,1),
  ('jean-paul-gaultier-divine','chiet','Chiết 10ml',10,340000,2),
  ('jean-paul-gaultier-divine','full','Full 100ml',100,2690000,3),
  ('dior-sauvage-elixir','chiet','Chiết 5ml',5,300000,1),
  ('dior-sauvage-elixir','chiet','Chiết 10ml',10,520000,2),
  ('dior-sauvage-elixir','full','Full 60ml',60,4290000,3),
  ('dior-addict-edp','chiet','Chiết 5ml',5,230000,1),
  ('dior-addict-edp','chiet','Chiết 10ml',10,390000,2),
  ('dior-addict-edp','full','Full 100ml',100,3290000,3),
  ('thomas-kosmala-no-4-apres-lamour','chiet','Chiết 5ml',5,270000,1),
  ('thomas-kosmala-no-4-apres-lamour','chiet','Chiết 10ml',10,450000,2),
  ('thomas-kosmala-no-4-apres-lamour','full','Full 100ml',100,4490000,3),
  ('afnan-9pm','chiet','Chiết 5ml',5,75000,1),
  ('afnan-9pm','chiet','Chiết 10ml',10,120000,2),
  ('afnan-9pm','full','Full 100ml',100,750000,3),
  ('montblanc-explorer-ultra-blue','chiet','Chiết 5ml',5,160000,1),
  ('montblanc-explorer-ultra-blue','chiet','Chiết 10ml',10,260000,2),
  ('montblanc-explorer-ultra-blue','full','Full 100ml',100,1890000,3),
  ('chanel-allure-homme-sport-edt','chiet','Chiết 5ml',5,210000,1),
  ('chanel-allure-homme-sport-edt','chiet','Chiết 10ml',10,360000,2),
  ('chanel-allure-homme-sport-edt','full','Full 100ml',100,3090000,3),
  ('carolina-herrera-212-men-sexy','chiet','Chiết 5ml',5,160000,1),
  ('carolina-herrera-212-men-sexy','chiet','Chiết 10ml',10,260000,2),
  ('carolina-herrera-212-men-sexy','full','Full 100ml',100,1890000,3),
  ('miss-dior-blooming-bouquet','chiet','Chiết 5ml',5,220000,1),
  ('miss-dior-blooming-bouquet','chiet','Chiết 10ml',10,380000,2),
  ('miss-dior-blooming-bouquet','full','Full 100ml',100,3190000,3),
  ('giorgio-armani-my-way-edp','chiet','Chiết 5ml',5,200000,1),
  ('giorgio-armani-my-way-edp','chiet','Chiết 10ml',10,340000,2),
  ('giorgio-armani-my-way-edp','full','Full 90ml',90,2690000,3),
  ('giorgio-armani-si-passione','chiet','Chiết 5ml',5,210000,1),
  ('giorgio-armani-si-passione','chiet','Chiết 10ml',10,360000,2),
  ('giorgio-armani-si-passione','full','Full 100ml',100,2890000,3);

-- PRODUCT ↔ COLLECTION (theo giới tính — để filter Nữ/Nam/Unisex đúng)
insert into product_collections(product_slug,collection_slug) values
  ('narciso-rodriguez-for-her-edp','nu'),
  ('narciso-rodriguez-for-her-edt','nu'),
  ('narciso-rodriguez-rouge','nu'),
  ('narciso-rodriguez-poudree','nu'),
  ('narciso-rodriguez-musc-noir','nu'),
  ('narciso-rodriguez-musc-noir-rose','nu'),
  ('narciso-rodriguez-pure-musc','nu'),
  ('narciso-rodriguez-fleur-musc','nu'),
  ('gucci-flora-gorgeous-jasmine','nu'),
  ('gucci-flora-gorgeous-gardenia','nu'),
  ('gucci-bloom','nu'),
  ('bleu-de-chanel-edp','nam'),
  ('dior-sauvage-edp','nam'),
  ('ysl-libre-edp','nu'),
  ('ysl-y-edp','nam'),
  ('ysl-black-opium-edp','nu'),
  ('ysl-mon-paris-edp','nu'),
  ('le-labo-another-13','unisex'),
  ('chanel-coco-mademoiselle-edp','nu'),
  ('chanel-n5-edp','nu'),
  ('miss-dior-edp','nu'),
  ('montblanc-signature','nu'),
  ('montblanc-legend-edt','nam'),
  ('montblanc-explorer-edp','nam'),
  ('giorgio-armani-acqua-di-gio-edt','nam'),
  ('jean-paul-gaultier-le-male-edt','nam'),
  ('jean-paul-gaultier-scandal-edp','nu'),
  ('burberry-her-edp','nu'),
  ('byredo-la-tulipe','nu'),
  ('dolce-and-gabbana-the-one-edp','nu'),
  ('prada-lhomme','nam'),
  ('xerjoff-torino-21','unisex'),
  ('initio-oud-for-greatness','unisex'),
  ('salvatore-ferragamo-signorina','nu'),
  ('loewe-aire','nu'),
  ('maison-alhambra-amber-oud-ruby-edition','unisex'),
  ('maison-alhambra-delilah','nu'),
  ('maison-alhambra-delilah-blanc','nu'),
  ('maison-alhambra-delilah-rose','nu'),
  ('maison-alhambra-musc-al-harair','unisex'),
  ('maison-alhambra-kismet','unisex'),
  ('jovoy-les-jeux-sont-faits','unisex'),
  ('montale-intense-cafe','unisex'),
  ('mancera-cedrat-boise','unisex'),
  ('armaf-club-de-nuit-intense-man','nam'),
  ('chanel-chance-edt','nu'),
  ('chanel-chance-eau-fraiche','nu'),
  ('versace-pour-homme','nam'),
  ('parfums-de-marly-valaya','nu'),
  ('parfums-de-marly-delina','nu'),
  ('dolce-and-gabbana-light-blue-edt','nu'),
  ('giorgio-armani-acqua-di-gioia','nu'),
  ('giorgio-armani-acqua-di-gio-profondo','nam'),
  ('prada-paradoxe','nu'),
  ('versace-eros-edt','nam'),
  ('jean-paul-gaultier-le-male-le-parfum','nam'),
  ('jean-paul-gaultier-divine','nu'),
  ('dior-sauvage-elixir','nam'),
  ('dior-addict-edp','nu'),
  ('thomas-kosmala-no-4-apres-lamour','unisex'),
  ('afnan-9pm','nam'),
  ('montblanc-explorer-ultra-blue','nam'),
  ('chanel-allure-homme-sport-edt','nam'),
  ('carolina-herrera-212-men-sexy','nam'),
  ('miss-dior-blooming-bouquet','nu'),
  ('giorgio-armani-my-way-edp','nu'),
  ('giorgio-armani-si-passione','nu')
on conflict do nothing;